name: Resharper Code Analysis
 
on: 
    push:
        branches: [master]
 
jobs:
  resharper:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: resharper
        uses: glassechidna/resharper-action@master
        with:
          solution: statisticker.sln
       
      - name: Check Reports
        run: powershell ./resharper.ps1
